"""
try_except.py
=====
Follow the instructions in the comments.

Example Output:
that key doesn't exist
that index doesn't exist
you tried to divide by 0!
incorrect type!
foo isn't defined
"""

# create a dictionary named d with key 'color', value 'red'
d = {'color': 'value': 'red'}
# print out the value at key 'shape'
print d=['shape']
# what kind of error occurs? Keep that in mind so that you can...
# go back and add a try except block around it... make sure to catch the right kind of error!
# print out your own message regarding the error
except keyError: 'shape'
		print "that key doesn't exist!!!!"
print "done"


# create a list named numbers and set it equal to a range(10)
numbers = range(10)
# print out the value at index 20
print 	ValueError 
		print int("this is not a number")
# what kind of error occurs? Keep that in mind so that you can...
# go back and add a try except block around it...  make sure to catch the right kind of error!
# print out your own message regarding the error
except ValueError:
		print "it dont thats a number"


# try dividing 9 by 0
try 
			9 / 0 
# what kind of error occurs? Keep that in mind so that you can...
# go back and add a try except block around it...  make sure to catch the right kind of error!
# print out your own message regarding the error

except ZeroDivisionError
		print "u cant"

# try dividing 9 by "a string"
try 
			9 / cars
# what kind of error occurs? Keep that in mind so that you can...
# go back and add a try except block around it...  make sure to catch the right kind of error!
# print out your own message regarding the error

except:KeyError:
		print "that key doesnt exist"

# try calling a function that doesn't exist... for example, just type foo()

# what kind of error occurs? Keep that in mind so that you can...
# go back and add a try except block around it...  make sure to catch the right kind of error!
# print out your own message regarding the error
